apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: sghai
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/sarikaghai-harborproject/app@sha256:5dd2b98f4b6b4699f30e84784ded3b1d161ac07b2297b7e06272a78c4badc223
        ports:
        - containerPort: 5432
